[package]
name = "nucleus"
version = "0.3.0"
edition = "2024"

[dependencies]
winit = { workspace = true }
wgpu = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

# Cada sistema operativo compila solo su backend gráfico
[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { workspace = true, features = ["vulkan"] }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { workspace = true, features = ["dx12", "vulkan"] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true, features = ["metal"] }
