[package]
name = "demo"
version = "0.2.3"
edition = "2021"

[dependencies]
nucleus    = { path = "../nucleus" }
winit      = { workspace = true }
wgpu       = { workspace = true }
pollster   = { workspace = true }
anyhow     = { workspace = true }
env_logger = { workspace = true }
log        = { workspace = true }